(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PlanarityModel=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const EPSILON=.001,VERTEX_RADIUS=30,BOUNDS={minX:50,maxX:950,minY:55,maxY:595};
const pairs=ids=>{const out=[];for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++)out.push([ids[i],ids[j]]);return out;};
const edgesFrom=pairs=>pairs.map(([from,to])=>({id:`${from}${to}`,from,to}));
const level=(id,title,type,ids,edges,positions,extra={})=>({id,title,type,vertices:ids.map(id=>({id,label:id})),edges,initialGeometry:{vertexPositions:positions,edgeBends:Object.fromEntries(edges.map(e=>[e.id,[]]))},...extra});
const LEVELS=[
 level('crossed-k4','Crossed K4','layout',['A','B','C','D'],edgesFrom(pairs(['A','B','C','D'])),{A:{x:220,y:150},B:{x:780,y:150},C:{x:780,y:520},D:{x:220,y:520}},{expectedFaces:4,hints:['The graph is K4. Try placing one vertex inside a triangle formed by the other three.','Move a corner toward the center of the other three vertices.']}),
 level('k23','K2,3 Routing Puzzle','layout',['A','B','1','2','3'],edgesFrom([['A','1'],['A','2'],['A','3'],['B','1'],['B','2'],['B','3']]),{A:{x:250,y:150},B:{x:750,y:150},1:{x:180,y:500},2:{x:500,y:500},3:{x:820,y:500}},{expectedFaces:3,hints:['Think of 1, 2, and 3 as three separate middle stops between A and B.','Select an outer route, add a bend, and route it around the outside.']}),
 level('cube','Flatten the Cube','layout',['A','B','C','D','E','F','G','H'],edgesFrom([['A','B'],['B','C'],['C','D'],['D','A'],['E','F'],['F','G'],['G','H'],['H','E'],['A','E'],['B','F'],['C','G'],['D','H']]),{A:{x:180,y:150},B:{x:820,y:150},C:{x:820,y:520},D:{x:180,y:520},E:{x:650,y:240},F:{x:350,y:240},G:{x:350,y:430},H:{x:650,y:430}},{expectedFaces:6,hints:['A cube can be drawn as one square inside another.','Use A–B–C–D as the outer square and E–F–G–H as the inner square.']}),
 level('k5','K5 Proof Challenge','proof',['A','B','C','D','E'],edgesFrom(pairs(['A','B','C','D','E'])),regularPolygon(['A','B','C','D','E'],500,325,245,-Math.PI/2),{proofKind:'k5',hints:['Trying more drawings does not prove impossibility. Switch to Proof.','Use Euler’s formula to find the number of faces under the planar assumption.']}),
 level('k33','K3,3 Proof Challenge','proof',['A','B','C','1','2','3'],edgesFrom([['A','1'],['A','2'],['A','3'],['B','1'],['B','2'],['B','3'],['C','1'],['C','2'],['C','3']]),{A:{x:220,y:150},B:{x:500,y:150},C:{x:780,y:150},1:{x:220,y:510},2:{x:500,y:510},3:{x:780,y:510}},{proofKind:'k33',hints:['Trying more drawings does not prove impossibility. Switch to Proof.','Bipartite graphs have no odd cycles. What does that imply about face boundaries?']})
];
function regularPolygon(ids,cx,cy,r,start){return Object.fromEntries(ids.map((id,i)=>{const a=start+i*2*Math.PI/ids.length;return[id,{x:cx+r*Math.cos(a),y:cy+r*Math.sin(a)}];}));}
function cloneGeometry(g){return{vertexPositions:Object.fromEntries(Object.entries(g.vertexPositions).map(([id,p])=>[id,{...p}])),edgeBends:Object.fromEntries(Object.entries(g.edgeBends).map(([id,ps])=>[id,ps.map(p=>({...p}))]))};}
function routePoints(level,geometry,edge){return[geometry.vertexPositions[edge.from],...(geometry.edgeBends[edge.id]||[]),geometry.vertexPositions[edge.to]];}
const cross=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);
const near=(a,b,eps=EPSILON)=>Math.hypot(a.x-b.x,a.y-b.y)<=eps;
function segmentIntersection(a,b,c,d){
 const r={x:b.x-a.x,y:b.y-a.y},s={x:d.x-c.x,y:d.y-c.y},rxs=r.x*s.y-r.y*s.x,qpxr=(c.x-a.x)*r.y-(c.y-a.y)*r.x;
 if(Math.abs(rxs)<=EPSILON&&Math.abs(qpxr)<=EPSILON){const rr=r.x*r.x+r.y*r.y;if(rr<=EPSILON)return near(a,c)?{type:'touch',point:{...a}}:null;const t0=((c.x-a.x)*r.x+(c.y-a.y)*r.y)/rr,t1=t0+(s.x*r.x+s.y*r.y)/rr,lo=Math.max(0,Math.min(t0,t1)),hi=Math.min(1,Math.max(t0,t1));if(hi-lo>EPSILON)return{type:'overlap',from:{x:a.x+lo*r.x,y:a.y+lo*r.y},to:{x:a.x+hi*r.x,y:a.y+hi*r.y}};if(hi>=lo-EPSILON)return{type:'touch',point:{x:a.x+lo*r.x,y:a.y+lo*r.y}};return null;}
 if(Math.abs(rxs)<=EPSILON)return null;const q={x:c.x-a.x,y:c.y-a.y},t=(q.x*s.y-q.y*s.x)/rxs,u=(q.x*r.y-q.y*r.x)/rxs;if(t>=-EPSILON&&t<=1+EPSILON&&u>=-EPSILON&&u<=1+EPSILON){const point={x:a.x+t*r.x,y:a.y+t*r.y};const interior=t>EPSILON&&t<1-EPSILON&&u>EPSILON&&u<1-EPSILON;return{type:interior?'proper':'touch',point,t,u};}return null;
}
function pointSegmentDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy;if(l2<=EPSILON)return Math.hypot(p.x-a.x,p.y-a.y);const t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l2));return Math.hypot(p.x-(a.x+t*dx),p.y-(a.y+t*dy));}
function segments(points){return points.slice(0,-1).map((a,i)=>({a,b:points[i+1],index:i}));}
function analyzeLayout(level,geometry){
 const properCrossings=[],overlaps=[],endpointConflicts=[],vertexEdgeConflicts=[],vertexOverlaps=[],bendVertexConflicts=[];
 const routes=new Map(level.edges.map(edge=>[edge.id,routePoints(level,geometry,edge)]));
 for(let i=0;i<level.vertices.length;i++)for(let j=i+1;j<level.vertices.length;j++){const a=level.vertices[i],b=level.vertices[j];if(Math.hypot(geometry.vertexPositions[a.id].x-geometry.vertexPositions[b.id].x,geometry.vertexPositions[a.id].y-geometry.vertexPositions[b.id].y)<VERTEX_RADIUS*2)vertexOverlaps.push({vertexA:a.id,vertexB:b.id});}
 for(const edge of level.edges){for(const bend of geometry.edgeBends[edge.id]||[])for(const vertex of level.vertices)if(Math.hypot(bend.x-geometry.vertexPositions[vertex.id].x,bend.y-geometry.vertexPositions[vertex.id].y)<VERTEX_RADIUS)bendVertexConflicts.push({edgeId:edge.id,vertexId:vertex.id});}
 for(let i=0;i<level.edges.length;i++)for(let j=i+1;j<level.edges.length;j++){const e1=level.edges[i],e2=level.edges[j],p1=routes.get(e1.id),p2=routes.get(e2.id),shared=[e1.from,e1.to].find(id=>id===e2.from||id===e2.to),sharedPoint=shared&&geometry.vertexPositions[shared];for(const s1 of segments(p1))for(const s2 of segments(p2)){const hit=segmentIntersection(s1.a,s1.b,s2.a,s2.b);if(!hit)continue;if(hit.type==='overlap'){overlaps.push({edgeA:e1.id,edgeB:e2.id});continue;}if(sharedPoint&&near(hit.point,sharedPoint))continue;const insideRoute1=!near(hit.point,p1[0])&&!near(hit.point,p1[p1.length-1]),insideRoute2=!near(hit.point,p2[0])&&!near(hit.point,p2[p2.length-1]);if(hit.type==='proper'||(insideRoute1&&insideRoute2))properCrossings.push({point:hit.point,edgeA:e1.id,edgeB:e2.id});else endpointConflicts.push({point:hit.point,edgeA:e1.id,edgeB:e2.id});}}
 for(const edge of level.edges)for(const segment of segments(routes.get(edge.id)))for(const vertex of level.vertices){if(vertex.id===edge.from||vertex.id===edge.to)continue;if(pointSegmentDistance(geometry.vertexPositions[vertex.id],segment.a,segment.b)<VERTEX_RADIUS-EPSILON)vertexEdgeConflicts.push({vertexId:vertex.id,edgeId:edge.id});}
 for(const edge of level.edges){const own=segments(routes.get(edge.id));for(let i=0;i<own.length;i++)for(let j=i+1;j<own.length;j++){const hit=segmentIntersection(own[i].a,own[i].b,own[j].a,own[j].b);if(hit&&(hit.type==='overlap'||j>i+1))overlaps.push({edgeA:edge.id,edgeB:edge.id});}}
 const dedupe=(items,keyFn)=>[...new Map(items.map(item=>[keyFn(item),item])).values()];
 const crossings=dedupe(properCrossings,c=>`${[c.edgeA,c.edgeB].sort().join('|')}|${c.point.x.toFixed(2)}|${c.point.y.toFixed(2)}`);
 const report={properCrossings:crossings,vertexEdgeConflicts:dedupe(vertexEdgeConflicts,x=>`${x.vertexId}|${x.edgeId}`),overlaps:dedupe(overlaps,x=>`${x.edgeA}|${x.edgeB}`),vertexOverlaps,bendVertexConflicts,endpointConflicts:dedupe(endpointConflicts,x=>`${x.edgeA}|${x.edgeB}|${x.point.x.toFixed(2)}|${x.point.y.toFixed(2)}`)};
 report.crossingCount=crossings.length;report.conflictCount=report.vertexEdgeConflicts.length+report.overlaps.length+report.vertexOverlaps.length+report.bendVertexConflicts.length+report.endpointConflicts.length;report.layoutIsValid=report.conflictCount===0;return report;
}
function clampPoint(p){return{x:Math.max(BOUNDS.minX,Math.min(BOUNDS.maxX,p.x)),y:Math.max(BOUNDS.minY,Math.min(BOUNDS.maxY,p.y))};}
function createGeometryHistory(initial){let geometry=cloneGeometry(initial),history=[],future=[];return{get geometry(){return cloneGeometry(geometry);},get canUndo(){return history.length>0;},get canRedo(){return future.length>0;},commit(next){history.push(cloneGeometry(geometry));geometry=cloneGeometry(next);future=[];},undo(){if(!history.length)return false;future.push(cloneGeometry(geometry));geometry=history.pop();return true;},redo(){if(!future.length)return false;history.push(cloneGeometry(geometry));geometry=future.pop();return true;},reset(){geometry=cloneGeometry(initial);history=[];future=[];}};}
function validateProof(kind,values){const expected=kind==='k5'?{faces:7,minBoundary:3,reason:'simple',required:21,available:20,inequality:'no',conclusion:'nonplanar'}:{faces:5,minBoundary:4,reason:'bipartite',required:20,available:18,inequality:'no',conclusion:'nonplanar'};const order=['faces','minBoundary','reason','required','available','inequality','conclusion'];const messages={faces:'Use Euler’s formula v − e + f = 2 to solve for f.',minBoundary:kind==='k5'?'A simple graph needs at least 3 boundary edges per face.':'A bipartite graph has no odd cycles, so a face needs at least 4 boundary edges.',reason:kind==='k5'?'K5 is simple, so triangular faces are the minimum.':'Use the bipartite structure: there are no odd cycles.',required:'Multiply the minimum boundary length by f.',available:'Each edge has two sides, so the available boundary count is 2e.',inequality:'Compare the required boundary count with the available edge sides.',conclusion:'A false necessary inequality contradicts the planar assumption.'};for(const key of order)if(String(values[key])!==String(expected[key]))return{valid:false,step:key,message:messages[key]};return{valid:true,step:'complete',message:'Contradiction complete.'};}
function topologySignature(level){return JSON.stringify({vertices:level.vertices.map(v=>v.id),edges:level.edges.map(e=>[e.id,e.from,e.to])});}
return{EPSILON,VERTEX_RADIUS,BOUNDS,LEVELS,cloneGeometry,routePoints,segmentIntersection,pointSegmentDistance,analyzeLayout,clampPoint,createGeometryHistory,validateProof,topologySignature};
});
