(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.OutcomeModel=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
let serial=0;const id=(prefix='id')=>`${prefix}-${++serial}`;const clone=value=>JSON.parse(JSON.stringify(value));
const option=(key,label)=>({id:key,label});
const group=(key,label,labels)=>({id:key,label,options:labels.map((text,i)=>option(`${key}-o${i+1}`,text))});
const stage=(key,label,fieldName,groups)=>({id:key,label,fieldName,groups});
const platform=()=>stage('platform','Platform','platform',[group('desktop','Desktop',['Windows','macOS','Linux']),group('mobile','Mobile',['Android','iOS'])]);
const auth=(key='authentication',labels=['Password','Passkey','SSO'])=>stage(key,'Authentication','authentication',[group(`${key}-methods`,'Methods',labels)]);
const network=(key='network')=>stage(key,'Network Mode','network',[group(`${key}-modes`,'Modes',['Normal','Degraded'])]);
const PRESETS={
  platform:{id:'platform',title:'Platform Matrix',model:{mode:'uniform',stages:[platform(),auth(),network()]}},
  character:{id:'character',title:'Character Builder',model:{mode:'uniform',stages:[stage('class','Class','characterClass',[group('standard','Standard',['Warrior','Ranger','Mage']),group('specialist','Specialist',['Engineer','Alchemist'])]),stage('map','Map','map',[group('maps','Maps',['Forest','Ruins','Harbor','Citadel'])]),stage('difficulty','Difficulty','difficulty',[group('difficulty-modes','Modes',['Normal','Veteran'])])]}},
  login:{id:'login',title:'Login Alternatives',model:{mode:'uniform',stages:[stage('login-method','Login Method','loginMethod',[group('institutional','Institutional',['College SSO','Google','Microsoft','GitHub']),group('hardware','Hardware Key',['USB Key','NFC Key','Phone Key'])])]}},
  conditional:{id:'conditional',title:'Conditional Platform Matrix',model:{mode:'conditional',rootStage:platform(),branches:[{id:'branch-desktop',rootGroupId:'desktop',stages:[auth('desktop-auth'),network('desktop-network')]},{id:'branch-mobile',rootGroupId:'mobile',stages:[auth('mobile-auth',['Passkey','SSO']),network('mobile-network')]}]}},
  channels:{id:'channels',title:'Build Channels',model:{mode:'conditional',rootStage:stage('channel','Channel','channel',[group('stable','Stable',['Public']),group('preview','Preview',['Beta','Nightly'])]),branches:[{id:'branch-stable',rootGroupId:'stable',stages:[stage('stable-arch','Architecture','architecture',[group('stable-arch-options','Architectures',['x64','ARM64'])])]},{id:'branch-preview',rootGroupId:'preview',stages:[stage('preview-arch','Architecture','architecture',[group('preview-arch-options','Architectures',['x64','ARM64'])]),stage('logging','Logging','logging',[group('logging-options','Levels',['Standard','Verbose','Trace'])])]}]}},
  tiny:{id:'tiny',title:'Tiny Verification Model',model:{mode:'uniform',stages:[stage('tiny-platform','Platform','platform',[group('tiny-platforms','Platforms',['Desktop','Mobile'])]),stage('build','Build','build',[group('builds','Builds',['Debug','Release'])])]}},
};
function loadPreset(key){if(!PRESETS[key])throw new RangeError(`Unknown preset: ${key}`);return clone(PRESETS[key].model)}
function flattenStageOptions(s){return s.groups.flatMap(g=>g.options.map(o=>({...o,groupId:g.id,groupLabel:g.label})))}
function stageCount(s){return s.groups.reduce((sum,g)=>sum+g.options.length,0)}
function pipelineProduct(stages){return stages.reduce((product,s)=>product*stageCount(s),1)}
function branchFor(model,groupId){return model.branches.find(b=>b.rootGroupId===groupId)}
function branchCount(model,branch){const root=model.rootStage.groups.find(g=>g.id===branch.rootGroupId);return(root?root.options.length:0)*pipelineProduct(branch.stages)}
function total(model){if(model.mode==='uniform')return pipelineProduct(model.stages);return model.rootStage.groups.reduce((sum,g)=>{const branch=branchFor(model,g.id);return sum+(branch?branchCount(model,branch):0)},0)}
function duplicate(values){const seen=new Set();for(const value of values){const key=value.trim().toLocaleLowerCase();if(seen.has(key))return value.trim();seen.add(key)}return null}
function validateStage(s,errors,pipeline){if(!s.label.trim())errors.push({id:s.id,field:'label',message:'Stage label is required.'});if(!s.fieldName.trim()||!toIdentifier(s.fieldName))errors.push({id:s.id,field:'fieldName',message:'A code-safe field name is required.'});if(!s.groups.length)errors.push({id:s.id,message:'Every stage needs at least one group.'});const groupDupe=duplicate(s.groups.map(g=>g.label));if(groupDupe)errors.push({id:s.id,message:`Group label "${groupDupe}" appears more than once.`});const labels=[];for(const g of s.groups){if(!g.label.trim())errors.push({id:g.id,message:'Group label is required.'});if(!g.options.length)errors.push({id:g.id,message:'Every group needs at least one option.'});for(const o of g.options){if(!o.label.trim())errors.push({id:o.id,message:'Option label is required.'});labels.push(o.label)}const own=duplicate(g.options.map(o=>o.label));if(own)errors.push({id:g.id,message:`Option "${own}" appears more than once.`})}const dupe=duplicate(labels);if(dupe)errors.push({id:s.id,message:`This stage is modeled with disjoint groups, but the option "${dupe}" appears more than once. Rename or remove the duplicate before counting.`});return pipeline}
function validatePipeline(stages,errors,name){const dupe=duplicate(stages.map(s=>s.label));if(dupe)errors.push({id:name,message:`Stage label "${dupe}" appears more than once in this pipeline.`});stages.forEach(s=>validateStage(s,errors,name))}
function validate(model){const errors=[];if(!model||!['uniform','conditional'].includes(model.mode))return[{id:'model',message:'Choose a valid modeling mode.'}];if(model.mode==='uniform'){if(!model.stages.length)errors.push({id:'model',message:'A uniform pipeline needs at least one stage.'});if(model.stages.length>4)errors.push({id:'model',message:'Uniform mode supports at most four stages.'});validatePipeline(model.stages,errors,'uniform')}else{validateStage(model.rootStage,errors,'root');if(model.rootStage.groups.length<2||model.rootStage.groups.length>4)errors.push({id:model.rootStage.id,message:'Conditional mode needs two to four root groups.'});for(const g of model.rootStage.groups){const matches=model.branches.filter(b=>b.rootGroupId===g.id);if(matches.length!==1)errors.push({id:g.id,message:'Every root group must have exactly one conditional branch.'});else{if(matches[0].stages.length>3)errors.push({id:matches[0].id,message:'A branch supports at most three downstream stages.'});validatePipeline(matches[0].stages,errors,matches[0].id)}}if(model.branches.some(b=>!model.rootStage.groups.some(g=>g.id===b.rootGroupId)))errors.push({id:'model',message:'A branch is detached from its root group.'})}for(const error of errors)if(!error.message)error.message='The model is incomplete.';if(!errors.length&&!Number.isSafeInteger(total(model)))errors.push({id:'model',message:'The total exceeds the largest safe integer.'});return errors}
function decode(stages,index){const radices=stages.map(stageCount),positions=new Array(stages.length);for(let i=stages.length-1;i>=0;i--){positions[i]=index%radices[i];index=Math.floor(index/radices[i])}return stages.map((s,i)=>{const value=flattenStageOptions(s)[positions[i]];return{stageId:s.id,stageLabel:s.label,fieldName:s.fieldName,...value}})}
function getOutcomeAt(model,index){const max=total(model);if(!Number.isInteger(index)||index<0||index>=max)throw new RangeError(`Outcome index must be from 0 to ${max-1}`);if(model.mode==='uniform')return{index,branchId:null,values:decode(model.stages,index)};let offset=0;for(const rootGroup of model.rootStage.groups){const branch=branchFor(model,rootGroup.id),count=branchCount(model,branch);if(index<offset+count){const local=index-offset,stages=[{...model.rootStage,groups:[rootGroup]},...branch.stages];return{index,branchId:branch.id,rootGroupId:rootGroup.id,values:decode(stages,local)}}offset+=count}throw new RangeError('Outcome was not found')}
function outcomes(model,limit=Infinity){const count=Math.min(total(model),limit);return Array.from({length:count},(_,i)=>getOutcomeAt(model,i))}
function stageNumeric(s){return s.groups.length>1?`(${s.groups.map(g=>g.options.length).join(' + ')})`:`${stageCount(s)}`}
function expression(model){if(model.mode==='uniform'){const symbolic=model.stages.map(s=>s.groups.length>1?`(${s.groups.map(g=>g.label).join(' + ')})`:s.label).join(' x ');const numeric=model.stages.map(stageNumeric).join(' x ');const simplified=model.stages.map(stageCount).join(' x ');return{symbolic,numeric,simplified,total:total(model),branchTotals:[]}}const branchTotals=model.rootStage.groups.map(g=>{const b=branchFor(model,g.id);return{label:g.label,numeric:[g.options.length,...b.stages.map(stageCount)].join(' x '),total:branchCount(model,b)}});return{symbolic:branchTotals.map(x=>`${x.label} branch`).join(' + '),numeric:branchTotals.map(x=>`(${x.numeric})`).join(' + '),simplified:branchTotals.map(x=>x.total).join(' + '),total:total(model),branchTotals}}
function accessibleExpression(model){const e=expression(model);return`${e.numeric.replaceAll(' x ',' times ').replaceAll(' + ',' plus ')} equals ${e.total} complete outcomes.`}
const RESERVED=new Set(['alignas','alignof','and','asm','auto','bool','break','case','catch','char','class','const','continue','default','delete','do','double','else','enum','explicit','export','extern','false','float','for','friend','goto','if','inline','int','long','namespace','new','not','operator','or','private','protected','public','register','return','short','signed','sizeof','static','struct','switch','template','this','throw','true','try','typedef','typename','union','unsigned','using','virtual','void','volatile','while']);
function toIdentifier(label){let text=String(label||'').replace(/C\+\+/gi,' cpp ').replace(/[^\p{L}\p{N}]+/gu,' ').trim();if(!text)return'';const parts=text.split(/\s+/),first=parts.shift().toLocaleLowerCase();let out=first+parts.map(p=>p.charAt(0).toLocaleUpperCase()+p.slice(1)).join('');out=out.replace(/^([0-9])/,'value$1');if(RESERVED.has(out))out+='Options';return out}
function uniqueIdentifiers(stages){const used=new Map();return stages.map(s=>{const base=toIdentifier(s.fieldName)||'choice';const n=(used.get(base)||0)+1;used.set(base,n);return n===1?base:`${base}${n}`})}
function escapeCpp(value){return String(value).replaceAll('\\','\\\\').replaceAll('"','\\"').replaceAll('\n','\\n')}
function commentText(value){return String(value).replace(/[\r\n]+/g,' ').replaceAll('*/','* /')}
function arrayBlock(s,name){const lines=[`vector<string> ${name}Options = {`];for(const g of s.groups){lines.push(`    // ${commentText(g.label)}`);for(const o of g.options)lines.push(`    "${escapeCpp(o.label)}",`)}lines.push('};');return lines.join('\n')}
function loopBlock(stages,names,indent='',rootName=null,rootArray=null){const lines=[];let depth=indent;if(rootName){lines.push(`${depth}for (const auto& ${rootName} : ${rootArray}) {`);depth+='    '}stages.forEach((s,i)=>{lines.push(`${depth}for (const auto& ${names[i]} : ${names[i]}Options) {`);depth+='    '});const args=[rootName,...names].filter(Boolean);lines.push(`${depth}emit(${args.join(', ')});`);for(let i=stages.length-1;i>=0;i--){depth=depth.slice(4);lines.push(`${depth}}`)}if(rootName){depth=depth.slice(4);lines.push(`${depth}}`)}return lines.join('\n')}
function generateCode(model){if(model.mode==='uniform'){const names=uniqueIdentifiers(model.stages),arrays=model.stages.map((s,i)=>arrayBlock(s,names[i])).join('\n\n');return`${arrays}\n\n${loopBlock(model.stages,names)}\n\n// ${total(model)} emit calls`}
const blocks=[];for(const rootGroup of model.rootStage.groups){const branch=branchFor(model,rootGroup.id),rootName=toIdentifier(model.rootStage.fieldName)||'rootChoice',rootArray=`${toIdentifier(rootGroup.label)||'branch'}${rootName.charAt(0).toUpperCase()+rootName.slice(1)}Options`,names=uniqueIdentifiers(branch.stages);blocks.push(`// ${commentText(rootGroup.label)} branch: ${branchCount(model,branch)} outcomes`,'{');blocks.push(`vector<string> ${rootArray} = { ${rootGroup.options.map(o=>`"${escapeCpp(o.label)}"`).join(', ')} };`);branch.stages.forEach((s,i)=>blocks.push(arrayBlock(s,names[i])));blocks.push(loopBlock(branch.stages,names,'',rootName,rootArray),'}','')}blocks.push(`// Total: ${total(model)} emit calls`);return blocks.join('\n\n')}
function structurallySameBranches(model){if(model.mode!=='conditional'||!model.branches.length)return false;const shape=stages=>JSON.stringify(stages.map(s=>({label:s.label,fieldName:s.fieldName,groups:s.groups.map(g=>({label:g.label,options:g.options.map(o=>o.label)}))})));return model.branches.every(b=>shape(b.stages)===shape(model.branches[0].stages))}
function freshen(value){const copy=clone(value);function walk(node){if(node&&typeof node==='object'){if('id'in node)node.id=id(node.id.split('-')[0]||'id');Object.values(node).forEach(walk)}}walk(copy);return copy}
function convertMode(model,target){if(model.mode===target)return clone(model);if(target==='conditional'){if(model.stages[0].groups.length<2)throw new Error('The first stage needs at least two groups.');const rootStage=freshen(model.stages[0]),branches=rootStage.groups.map((g,i)=>({id:id('branch'),rootGroupId:g.id,stages:freshen(model.stages.slice(1))}));return{mode:'conditional',rootStage,branches}}if(!structurallySameBranches(model))throw new Error('Conditional branches do not share one uniform downstream pipeline.');return{mode:'uniform',stages:[freshen(model.rootStage),...freshen(model.branches[0].stages)]}}
return{PRESETS,id,clone,loadPreset,flattenStageOptions,stageCount,pipelineProduct,branchFor,branchCount,total,validate,getOutcomeAt,outcomes,expression,accessibleExpression,toIdentifier,generateCode,structurallySameBranches,convertMode,freshen};});
