(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ColoringModel=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const V=(id,label,x,y)=>({id,label,x,y}),E=(id,u,v)=>({id,u,v}),pairs=ids=>{const out=[];for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++)out.push([ids[i],ids[j]]);return out},polygon=(prefix,n,cx=450,cy=300,r=220)=>Array.from({length:n},(_,i)=>{const a=-Math.PI/2+i*2*Math.PI/n;return V(`${prefix}${i}`,`${prefix==='player'?'Player ':prefix.toUpperCase()}${i}`,cx+r*Math.cos(a),cy+r*Math.sin(a))});
const levels=[];
levels.push({id:'tree',title:'Behavior Tree',family:'Tree',vertices:[V('core','Choose Action',450,80),V('gate','Enemy Visible?',190,260),V('market','Health Low?',450,260),V('tower','Patrol',710,260),V('vault','Attack',90,480),V('lab','Take Cover',290,480),V('docks','Heal',450,480)],edges:[E('t_cg','core','gate'),E('t_cm','core','market'),E('t_ct','core','tower'),E('t_gv','gate','vault'),E('t_gl','gate','lab'),E('t_md','market','docks')],facts:{maximumDegree:3,cliqueNumber:2,vertexChromaticNumber:2,edgeChromaticIndex:3,maximumCliqueVertexIds:['core','gate']},fixtures:{vertex:{core:1,vault:1,lab:1,docks:1,gate:2,market:2,tower:2},edge:{t_cg:1,t_md:1,t_cm:2,t_gv:2,t_ct:3,t_gl:3}},prompt:'Why can jobs at the same tree depth reuse a channel, while three edges at Choose Action need three rounds?'});
const bVerts=[V('c1','Client 1',160,150),V('c2','Client 2',450,150),V('c3','Client 3',740,150),V('s1','Server 1',160,450),V('s2','Server 2',450,450),V('s3','Server 3',740,450)],bEdges=[];for(let i=1;i<=3;i++)for(let j=1;j<=3;j++)bEdges.push(E(`b_c${i}s${j}`,`c${i}`,`s${j}`));const bEdgeFix={};for(let i=0;i<3;i++)for(let j=0;j<3;j++)bEdgeFix[`b_c${i+1}s${j+1}`]=(i+j)%3+1;levels.push({id:'k33',title:'Client-Server Grid',family:'K3,3',vertices:bVerts,edges:bEdges,facts:{maximumDegree:3,cliqueNumber:2,vertexChromaticNumber:2,edgeChromaticIndex:3,maximumCliqueVertexIds:['c1','s1']},fixtures:{vertex:{c1:1,c2:1,c3:1,s1:2,s2:2,s3:2},edge:bEdgeFix},prompt:'Why can all clients reuse one vertex color, while every server needs three different incident edge colors?'});
function cycleLevel(id,title,prefix,n,chi){const vertices=polygon(prefix,n),edges=[];for(let i=0;i<n;i++)edges.push(E(`${prefix}_${i}${(i+1)%n}`,`${prefix}${i}`,`${prefix}${(i+1)%n}`));const vertex={},edge={};for(let i=0;i<n;i++){vertex[`${prefix}${i}`]=i===n-1&&n%2?3:i%2+1;edge[`${prefix}_${i}${(i+1)%n}`]=i===n-1&&n%2?3:i%2+1}return{id,title,family:`C${n}`,vertices,edges,facts:{maximumDegree:2,cliqueNumber:2,vertexChromaticNumber:chi,edgeChromaticIndex:chi,maximumCliqueVertexIds:[`${prefix}0`,`${prefix}1`]},fixtures:{vertex,edge},prompt:n%2?'Why does two-color alternation fail when this odd ring closes?':'What makes two-color alternation close cleanly on this even ring?'}}
levels.push(cycleLevel('c6','Even Patrol Ring','e',6,2));levels.push(cycleLevel('c5','Odd Patrol Ring','o',5,3));
function completeLevel(id,title,prefix,n,chiEdge){const vertices=polygon(prefix,n,450,300,n===6?235:230),edges=pairs(vertices.map(v=>v.id)).map(([u,v])=>E(`${prefix[0]}_${u.replace(prefix,'')}${v.replace(prefix,'')}`,u,v)),vertex={},edge={};vertices.forEach((v,i)=>vertex[v.id]=i+1);if(n===5)for(const e of edges){const i=+e.u.replace(prefix,''),j=+e.v.replace(prefix,'');edge[e.id]=(i+j)%5+1}return{id,title,family:`K${n}`,vertices,edges,facts:{maximumDegree:n-1,cliqueNumber:n,vertexChromaticNumber:n,edgeChromaticIndex:chiEdge,maximumCliqueVertexIds:vertices.map(v=>v.id)},fixtures:{vertex,edge},prompt:`Why does K${n} need ${n} vertex colors but ${chiEdge} edge-color rounds?`}}
levels.push(completeLevel('k5','All-to-All Squad','k',5,5));
const pVerts=[V('capital','Capital',450,110),V('harbor','Harbor',180,480),V('highlands','Highlands',720,480),V('frontier','Frontier',450,335)],pEdges=[E('p_ch','capital','harbor'),E('p_ci','capital','highlands'),E('p_cf','capital','frontier'),E('p_hi','harbor','highlands'),E('p_hf','harbor','frontier'),E('p_if','highlands','frontier')];levels.push({id:'k4',title:'Four Kingdoms',family:'Planar K4',planar:true,vertices:pVerts,edges:pEdges,facts:{maximumDegree:3,cliqueNumber:4,vertexChromaticNumber:4,edgeChromaticIndex:3,maximumCliqueVertexIds:pVerts.map(v=>v.id)},fixtures:{vertex:{capital:1,harbor:2,highlands:3,frontier:4},edge:{p_ch:1,p_if:1,p_ci:2,p_hf:2,p_cf:3,p_hi:3}},prompt:'How does the four-vertex clique prove four colors are necessary without contradicting the Four Color Theorem?'});
const sVerts=[V('matchmaking','Matchmaking',220,150),V('world_save','World Save',680,150),V('analytics','Analytics',680,470),V('anti_cheat','Anti-Cheat',220,470),V('content_update','Content Update',450,310)],sEdges=[E('s_mw','matchmaking','world_save'),E('s_wa','world_save','analytics'),E('s_aa','analytics','anti_cheat'),E('s_am','anti_cheat','matchmaking'),E('s_cm','content_update','matchmaking'),E('s_cw','content_update','world_save'),E('s_ca','content_update','analytics'),E('s_cc','content_update','anti_cheat')];levels.push({id:'scheduler',title:'Game Server Scheduler',family:'Wheel W5',planar:true,vertices:sVerts,edges:sEdges,facts:{maximumDegree:4,cliqueNumber:3,vertexChromaticNumber:3,edgeChromaticIndex:4,maximumCliqueVertexIds:['matchmaking','world_save','content_update']},fixtures:{vertex:{matchmaking:1,analytics:1,world_save:2,anti_cheat:2,content_update:3},edge:{s_cm:1,s_aa:1,s_cw:2,s_am:2,s_ca:3,s_mw:3,s_cc:4,s_wa:4}},prompt:'Which nonadjacent jobs can safely share a channel, and how does the triangle prove the lower bound?'});
const k6=completeLevel('k6','Six-Player Tournament','player',6,5);k6.edges.forEach(e=>e.id=`q_${e.u.replace('player','')}${e.v.replace('player','')}`);k6.fixtures.edge={q_05:1,q_14:1,q_23:1,q_04:2,q_35:2,q_12:2,q_03:3,q_24:3,q_15:3,q_02:4,q_13:4,q_45:4,q_01:5,q_25:5,q_34:5};k6.prompt='Why is each edge-color class a matching in a five-round tournament schedule?';levels.push(k6);
function graphFacts(level){const degrees=new Map(level.vertices.map(v=>[v.id,0])),adjacency=new Map(level.vertices.map(v=>[v.id,new Set()])),incidentEdges=new Map(level.vertices.map(v=>[v.id,[]]));for(const e of level.edges){degrees.set(e.u,degrees.get(e.u)+1);degrees.set(e.v,degrees.get(e.v)+1);adjacency.get(e.u).add(e.v);adjacency.get(e.v).add(e.u);incidentEdges.get(e.u).push(e.id);incidentEdges.get(e.v).push(e.id)}return{vertexCount:level.vertices.length,edgeCount:level.edges.length,degrees,maximumDegree:Math.max(...degrees.values()),adjacency,incidentEdges}}
function normalizeAssignments(ids,input){const map=input instanceof Map?new Map(input):new Map(Object.entries(input||{}).map(([k,v])=>[k,v]));for(const id of ids)if(!map.has(id))map.set(id,null);return map}
function vertexConflicts(level,colors){const result=[];for(const e of level.edges){const c=colors.get(e.u);if(c!=null&&c===colors.get(e.v))result.push({edgeId:e.id,vertexA:e.u,vertexB:e.v,colorId:c})}return result}
function edgeConflicts(level,colors){const facts=graphFacts(level),result=[],seen=new Set();for(const v of level.vertices){const groups=new Map();for(const id of facts.incidentEdges.get(v.id)){const c=colors.get(id);if(c!=null){if(!groups.has(c))groups.set(c,[]);groups.get(c).push(id)}}for(const[colorId,ids]of groups)for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const pair=[ids[i],ids[j]].sort(),key=pair.join('|');if(!seen.has(key)){seen.add(key);result.push({sharedVertexId:v.id,edgeAId:pair[0],edgeBId:pair[1],colorId})}}}return result}
function derive(level,mode,input){const ids=(mode==='vertex'?level.vertices:level.edges).map(x=>x.id),colors=normalizeAssignments(ids,input),conflicts=mode==='vertex'?vertexConflicts(level,colors):edgeConflicts(level,colors),assignedCount=[...colors.values()].filter(x=>x!=null).length,colorsUsed=new Set([...colors.values()].filter(x=>x!=null)).size,totalCount=ids.length,status=assignedCount<totalCount?'incomplete':conflicts.length?'improper':'proper',target=mode==='vertex'?level.facts.vertexChromaticNumber:level.facts.edgeChromaticIndex,targetStatus=status!=='proper'?'Not reached':colorsUsed===target?'Target reached':colorsUsed>target?'Proper but above target':'Not reached';return{colors,conflicts,assignedCount,totalCount,colorsUsed,status,target,targetStatus,targetReached:targetStatus==='Target reached'}}
function cliqueIsComplete(level){const facts=graphFacts(level),clique=level.facts.maximumCliqueVertexIds;return clique.length===level.facts.cliqueNumber&&clique.every((u,i)=>clique.slice(i+1).every(v=>facts.adjacency.get(u).has(v)))}
function createSession(level){const colors={vertex:normalizeAssignments(level.vertices.map(v=>v.id),{}),edge:normalizeAssignments(level.edges.map(e=>e.id),{})},history={vertex:[],edge:[]};let mode='vertex';return{get mode(){return mode},getColors(m=mode){return new Map(colors[m])},setMode(m){mode=m},assign(id,color){const valid=(mode==='vertex'?level.vertices:level.edges).some(x=>x.id===id);if(!valid)return false;history[mode].push(new Map(colors[mode]));colors[mode].set(id,color);return true},undo(){if(!history[mode].length)return false;colors[mode]=history[mode].pop();return true},reset(){colors[mode]=normalizeAssignments((mode==='vertex'?level.vertices:level.edges).map(x=>x.id),{});history[mode]=[]},get canUndo(){return history[mode].length>0}}}
function hint(level,mode,analysis,step=0){if(analysis.conflicts.length)return mode==='vertex'?`Resolve the conflict on ${analysis.conflicts[0].edgeId}.`:`Resolve the incident-edge conflict at ${analysis.conflicts[0].sharedVertexId}.`;if(step===0)return mode==='vertex'?'Highlight the known maximum clique for a lower bound.':`At a degree-${level.facts.maximumDegree} vertex, all incident edges need different colors.`;return mode==='vertex'?`Use the ${level.family} structure to reuse colors only on nonadjacent vertices.`:'Each color class should form a matching of nonincident edges.'}
return{LEVELS:levels,graphFacts,normalizeAssignments,vertexConflicts,edgeConflicts,derive,cliqueIsComplete,createSession,hint};});
