'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const M=require('./edge-patrol-model.js');const L=i=>M.LEVELS[i];
test('initial graph facts match all five specifications',()=>{const expected=[[[2,2,4,2,2],[],6,'circuit'],[[2,2,4,2,3,1],['forge','exit'],7,'openTrail'],[[3,3,3,3],['alpha','beta','gamma','delta'],6,'neither'],[[4,1,1,1,1],['north','east','south','west'],4,'neither'],[[3,3,5,3],['north_bank','south_bank','island','east_bank'],7,'neither']];M.LEVELS.forEach((l,i)=>{const f=M.analyze(l,M.initialActiveIds(l));assert.deepEqual([...f.degreesByVertex.values()],expected[i][0]);assert.deepEqual(f.oddVertexIds,expected[i][1]);assert.equal(f.activeEdgeCount,expected[i][2]);assert.equal(f.classification,expected[i][3]);assert.equal(f.edgeBearingConnected,true);assert.equal(f.handshakeVerified,true)});assert.equal(new Set(L(4).edgePool.filter(e=>e.initiallyActive).map(e=>e.id)).size,7)});
test('edge-bearing connectivity ignores isolates and no-edge graph is distinct',()=>{const l=L(1),single=new Set(['l2_dr']);let f=M.analyze(l,single);assert.equal(f.edgeBearingConnected,true);assert.equal(f.componentCount,5);f=M.analyze(l,new Set());assert.equal(f.classification,'noEdges');assert.equal(f.edgeBearingConnected,false)});
test('specified repairs produce open trails and circuits',()=>{let a=M.initialActiveIds(L(1));a.add('l2_fx_2');assert.equal(M.analyze(L(1),a).classification,'circuit');a=M.initialActiveIds(L(2));a.delete('l3_ag');assert.equal(M.analyze(L(2),a).classification,'openTrail');a.delete('l3_bd');assert.equal(M.analyze(L(2),a).classification,'circuit');a=M.initialActiveIds(L(3));a.add('l4_ne');assert.equal(M.analyze(L(3),a).classification,'openTrail');a.add('l4_sw');assert.equal(M.analyze(L(3),a).classification,'circuit');a=M.initialActiveIds(L(4));a.add('l5_ns');a.add('l5_ie_2');assert.equal(M.analyze(L(4),a).classification,'circuit')});
function runEuler(level,vertices){const active=M.initialActiveIds(level);let route=M.emptyRoute();for(const v of vertices){const r=M.addEulerStep(level,active,route,v);assert.equal(r.accepted,true);route=r.route}return{route,status:M.routeStatus(level,active,route,'euler')}}
test('canonical Euler circuit and trail (both directions) validate',()=>{let r=runEuler(L(0),['spawn','armory','courtyard','tower','boss','courtyard','spawn']);assert.equal(r.status.completion,'Complete circuit');r=runEuler(L(1),['exit','forge','archive','core','dock','relay','core','forge']);assert.equal(r.status.completion,'Complete trail');r=runEuler(L(1),['forge','core','relay','dock','core','archive','forge','exit']);assert.equal(r.status.completion,'Complete trail')});
test('illegal Euler moves are rejected without mutation and parallel IDs each work',()=>{const l=L(0),a=M.initialActiveIds(l);let route=M.addEulerStep(l,a,M.emptyRoute(),'spawn').route;const before=JSON.stringify(route);let bad=M.addEulerStep(l,a,route,'tower');assert.equal(bad.reason,'nonadjacent');assert.equal(JSON.stringify(route),before);route=M.addEulerStep(l,a,route,'armory').route;bad=M.addEulerStep(l,a,route,'spawn');assert.equal(bad.reason,'reuse');const l2=L(1),p=M.initialActiveIds(l2);p.add('l2_fx_2');let pr=M.emptyRoute();for(const v of ['forge','exit','forge'])pr=M.addEulerStep(l2,p,pr,v).route;assert.deepEqual(pr.edgeIds,['l2_fx','l2_fx_2'])});
test('stuck route, undo, and restart semantics remain separate from graph facts',()=>{const l=L(0),a=M.initialActiveIds(l);let r=M.emptyRoute();for(const v of ['spawn','armory','courtyard','spawn'])r=M.addEulerStep(l,a,r,v).route;assert.equal(M.routeStatus(l,a,r,'euler').stuck,true);const undone=M.undoRoute(r);assert.equal(undone.vertexIds.at(-1),'courtyard');assert.equal(M.analyze(l,a).classification,'circuit');assert.deepEqual(M.emptyRoute().vertexIds,[])});
test('Hamilton analysis matches fixtures and parallel adjacency is collapsed',()=>{assert.deepEqual(M.LEVELS.map(l=>!!M.hamilton(l,M.initialActiveIds(l))),[true,true,true,false,true]);assert.equal(!!M.hamilton(L(2),M.initialActiveIds(L(2)),true),true);assert.equal(M.hamilton(L(0),M.initialActiveIds(L(0)),true),null);assert.equal(M.hamilton(L(1),M.initialActiveIds(L(1)),true),null);let a=M.initialActiveIds(L(3));a.add('l4_ne');a.add('l4_sw');assert.ok(M.hamilton(L(3),a));const f=M.analyze(L(4),M.initialActiveIds(L(4)));assert.equal(f.simpleNeighborSets.get('north_bank').size,2);assert.equal(f.adjacencyByEdge.get('north_bank').length,3)});
test('Hamilton validation rejects revisit and completes with unused edges',()=>{const l=L(2),a=M.initialActiveIds(l);let r=M.emptyRoute();for(const v of ['alpha','beta','gamma','delta']){const x=M.addHamiltonStep(l,a,r,v);assert.equal(x.accepted,true);r=x.route}assert.equal(M.routeStatus(l,a,r,'hamilton').completion,'Complete Hamilton path');assert.ok(r.edgeIds.length<a.size);const bad=M.addHamiltonStep(l,a,r,'alpha');assert.equal(bad.reason,'revisit')});
test('repair toggles parity at two endpoints and state transitions preserve required boundaries',()=>{const l=L(1),s=M.createSession(l),before=M.analyze(l,s.state.activeIds);s.setPrediction('openTrail',true);s.setRoute(runEuler(l,['exit','forge']).route);s.toggleEdge('l2_fx_2');const after=M.analyze(l,s.state.activeIds);assert.equal([...before.degreesByVertex].filter(([id,d])=>after.degreesByVertex.get(id)!==d).length,2);assert.equal(s.state.prediction,null);assert.deepEqual(s.state.route.vertexIds,[]);s.undoRepair();assert.deepEqual([...s.state.activeIds],[...M.initialActiveIds(l)]);s.toggleEdge('l2_xd');const repaired=[...s.state.activeIds];s.switchObjective('hamilton');assert.deepEqual([...s.state.activeIds],repaired);assert.equal(s.state.prediction,null);s.reset();assert.deepEqual([...s.state.activeIds],[...M.initialActiveIds(l)])});
test('inline UI script parses',()=>{const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8'),scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(x=>x[1]).filter(Boolean);assert.doesNotThrow(()=>new Function(scripts.at(-1)))});
