(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.RelationModel=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const base=[['a','A',450,90],['b','B',710,300],['c','C',450,510],['d','D',190,300]].map(([id,label,x,y])=>({id,label,shortLabel:label,x,y}));
const P=(id,title,description,elements,pairs,expected)=>({id,title,description,elements,pairs,expected});
const loops=['a','b','c','d'].map(x=>[x,x]),universal=[];for(const a of ['a','b','c','d'])for(const b of ['a','b','c','d'])universal.push([a,b]);
const modEls=[['n0','0',450,70],['n1','1',690,190],['n2','2',690,430],['n3','3',450,550],['n4','4',210,430],['n5','5',210,190]].map(([id,label,x,y])=>({id,label,shortLabel:label,x,y}));
const PRESETS=[
P('empty','Empty Sandbox','Vacuous truth and missing reflexivity.',base,[],{reflexive:false,irreflexive:true,symmetric:true,antisymmetric:true,transitive:true,equivalence:false}),
P('identity','Identity Relation','Both symmetric and antisymmetric.',base,loops,{reflexive:true,irreflexive:false,symmetric:true,antisymmetric:true,transitive:true,equivalence:true,partition:[['a'],['b'],['c'],['d']]}),
P('chain','Broken State Chain','A missing shortcut breaks transitivity.',base,[['a','b'],['b','c'],['c','d']],{reflexive:false,irreflexive:true,symmetric:false,antisymmetric:true,transitive:false,equivalence:false}),
P('near','Near Equivalence','Reflexive and symmetric, but not transitive.',base,[...loops,['a','b'],['b','a'],['b','c'],['c','b']],{reflexive:true,irreflexive:false,symmetric:true,antisymmetric:false,transitive:false,equivalence:false}),
P('order','Clearance Order','A reflexive, antisymmetric, transitive order.',base,[['a','a'],['a','b'],['a','c'],['a','d'],['b','b'],['b','c'],['b','d'],['c','c'],['c','d'],['d','d']],{reflexive:true,irreflexive:false,symmetric:false,antisymmetric:true,transitive:true,equivalence:false}),
P('mod3','Matchmaking Shards Modulo 3','Computing-rule equivalence classes.',modEls,[['n0','n0'],['n0','n3'],['n3','n0'],['n3','n3'],['n1','n1'],['n1','n4'],['n4','n1'],['n4','n4'],['n2','n2'],['n2','n5'],['n5','n2'],['n5','n5']],{reflexive:true,irreflexive:false,symmetric:true,antisymmetric:false,transitive:true,equivalence:true,partition:[['n0','n3'],['n1','n4'],['n2','n5']]}),
P('universal','Universal Relation','One dense equivalence class.',base,universal,{reflexive:true,irreflexive:false,symmetric:true,antisymmetric:false,transitive:true,equivalence:true,partition:[['a','b','c','d']]})];
function createMatrix(rows,cols=rows){return Array.from({length:rows},()=>Array(cols).fill(false))}function cloneMatrix(m){return m.map(r=>[...r])}function matrixFromPairs(elements,pairs){const index=new Map(elements.map((e,i)=>[e.id,i])),m=createMatrix(elements.length);for(const[a,b]of pairs)m[index.get(a)][index.get(b)]=true;return m}function pairsFromMatrix(m){const out=[];for(let i=0;i<m.length;i++)for(let j=0;j<m[i].length;j++)if(m[i][j])out.push([i,j]);return out}function inverse(m){return Array.from({length:m[0]?.length||0},(_,j)=>Array.from({length:m.length},(_,i)=>!!m[i][j]))}
function analyze(m){
 const n=m.length,empty=!m.some(row=>row.some(Boolean));let rw=null,iw=null,sw=null,aw=null,tw=null;
 for(let a=0;a<n;a++)if(!m[a][a]){rw=a;break}
 for(let a=0;a<n;a++)if(m[a][a]){iw=a;break}
 outer:for(let a=0;a<n;a++)for(let b=0;b<n;b++)if(m[a][b]&&!m[b][a]){sw=[a,b];break outer}
 outer:for(let a=0;a<n;a++)for(let b=a+1;b<n;b++)if(m[a][b]&&m[b][a]){aw=[a,b];break outer}
 outer:for(let a=0;a<n;a++)for(let b=0;b<n;b++)for(let c=0;c<n;c++)if(m[a][b]&&m[b][c]&&!m[a][c]){tw=[a,b,c];break outer}
 const result={reflexive:{value:rw===null,witness:rw},irreflexive:{value:iw===null,witness:iw},symmetric:{value:sw===null,witness:sw,vacuous:empty},antisymmetric:{value:aw===null,witness:aw,vacuous:empty},transitive:{value:tw===null,witness:tw,vacuous:empty}};
 result.equivalence=result.reflexive.value&&result.symmetric.value&&result.transitive.value;return result
}
function equivalenceClasses(m){if(!analyze(m).equivalence)return null;const visited=new Set(),classes=[];for(let a=0;a<m.length;a++){if(visited.has(a))continue;const current=[];for(let b=0;b<m.length;b++)if(m[a][b])current.push(b);current.forEach(b=>visited.add(b));classes.push(current)}return classes}
function compose(U,H){const out=createMatrix(U.length,H[0]?.length||0);for(let p=0;p<U.length;p++)for(let z=0;z<out[p].length;z++)for(let s=0;s<U[p].length;s++)if(U[p][s]&&H[s][z]){out[p][z]=true;break}return out}function compositionWitnesses(U,H,p,z){const out=[];for(let s=0;s<U[p].length;s++)if(U[p][s]&&H[s][z])out.push(s);return out}
function propertyExplanation(id,result,labels){const L=i=>labels[i];if(result.value){if(result.vacuous)return'No present pair or two-step chain violates the rule, so the universal statement is vacuously true.';const passed={reflexive:`All ${labels.length} required loops are present.`,irreflexive:`No element is related to itself; all ${labels.length} loops are absent.`,symmetric:'Every present ordered pair has its reverse pair.',antisymmetric:'No two distinct elements are related in both directions.',transitive:'Every two-step relation chain has its required shortcut pair.'};return passed[id]}const w=result.witness;if(id==='reflexive')return`(${L(w)},${L(w)}) is missing.`;if(id==='irreflexive')return`(${L(w)},${L(w)}) is present.`;if(id==='symmetric')return`(${L(w[0])},${L(w[1])}) is present, but (${L(w[1])},${L(w[0])}) is missing.`;if(id==='antisymmetric')return`${L(w[0])} and ${L(w[1])} are distinct, and both reverse pairs are present.`;return`(${L(w[0])},${L(w[1])}) and (${L(w[1])},${L(w[2])}) are present, but (${L(w[0])},${L(w[2])}) is missing.`}
function createInspectSession(preset){let matrix=matrixFromPairs(preset.elements,preset.pairs),history=[];return{get matrix(){return cloneMatrix(matrix)},get canUndo(){return history.length>0},toggle(i,j){history.push(cloneMatrix(matrix));matrix[i][j]=!matrix[i][j]},clear(){history.push(cloneMatrix(matrix));matrix=createMatrix(matrix.length)},undo(){if(!history.length)return false;matrix=history.pop();return true},reset(){matrix=matrixFromPairs(preset.elements,preset.pairs);history=[]}}}
const COMPOSITION={players:['Ari','Bo','Cy'],servers:['North','East','West'],zones:['Forest','Ruins','Arena'],initialU:[[true,false,false],[true,true,false],[false,false,true]],initialH:[[true,false,false],[false,true,true],[false,false,true]]};function createCompositionSession(){let U=cloneMatrix(COMPOSITION.initialU),H=cloneMatrix(COMPOSITION.initialH),history=[];return{get U(){return cloneMatrix(U)},get H(){return cloneMatrix(H)},get canUndo(){return history.length>0},toggle(which,i,j){history.push({U:cloneMatrix(U),H:cloneMatrix(H)});(which==='U'?U:H)[i][j]=!(which==='U'?U:H)[i][j]},clear(which){history.push({U:cloneMatrix(U),H:cloneMatrix(H)});if(which==='U')U=createMatrix(3);else H=createMatrix(3)},undo(){if(!history.length)return false;const p=history.pop();U=p.U;H=p.H;return true},reset(){U=cloneMatrix(COMPOSITION.initialU);H=cloneMatrix(COMPOSITION.initialH);history=[]}}}
return{PRESETS,COMPOSITION,createMatrix,cloneMatrix,matrixFromPairs,pairsFromMatrix,inverse,analyze,equivalenceClasses,compose,compositionWitnesses,propertyExplanation,createInspectSession,createCompositionSession};});
