(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.OrderModel=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
const DEFAULT_NAMES=['Ari','Blake','Chen','Divya','Elena','Faisal','Grace','Hugo','Imani','Jordan'],IDS=['obj-ari','obj-blake','obj-chen','obj-divya','obj-elena','obj-faisal','obj-grace','obj-hugo','obj-imani','obj-jordan'],COLORS=['blue','green','gold','purple','red','teal','navy','olive','magenta','gray'],ROLE_NAMES=['Lead','Tester','Deployer','Communicator','Observer'];
function objects(labels=DEFAULT_NAMES){return IDS.map((id,i)=>({id,label:labels[i]??DEFAULT_NAMES[i],shortLabel:String.fromCharCode(65+i),colorRole:COLORS[i]}))}
function roles(labels=ROLE_NAMES){return ROLE_NAMES.map((_,i)=>({id:`role-${i+1}`,label:labels[i]??ROLE_NAMES[i]}))}
function makeState({id,mode,n,k,title,objectNoun='engineer',group='team',ordered='role assignment',labels,roleLabels}){const selected=Array.from({length:k},(_,i)=>i);return{mode,n,k,objects:objects(labels),roles:roles(roleLabels),language:{title,objectNoun,groupOutcomeNoun:group,orderedOutcomeNoun:ordered},selectedGroupIndices:[...selected],selectedOrderIndices:[...selected],globalOutcomePage:0,bundlePage:0,selectedCodeStep:0,activePresetId:id}}
const PRESETS={
 response:{id:'response',title:'Response Team',state:makeState({id:'response',mode:'unordered',n:8,k:3,title:'Incident Response Team',group:'response team'})},
 roles:{id:'roles',title:'Incident Roles',state:makeState({id:'roles',mode:'ordered',n:8,k:3,title:'Incident Role Assignment'})},
 alerts:{id:'alerts',title:'Alert Ranking',state:makeState({id:'alerts',mode:'ordered',n:10,k:3,title:'Alert Priority Ranking',objectNoun:'alert',group:'alert set',ordered:'alert ranking',labels:Array.from({length:10},(_,i)=>`Alert ${String.fromCharCode(65+i)}`),roleLabels:['Priority 1','Priority 2','Priority 3']})},
 features:{id:'features',title:'Feature Set',state:makeState({id:'features',mode:'unordered',n:10,k:4,title:'Enabled Feature Set',objectNoun:'feature',group:'feature set',ordered:'enablement order',labels:['Chat','Trading','Parties','Replays','Anti-Cheat','Analytics','Voice','Spectator','Events','Matchmaking']})},
 failover:{id:'failover',title:'Failover Sequence',state:makeState({id:'failover',mode:'ordered',n:6,k:4,title:'Service Failover Sequence',objectNoun:'service',group:'service set',ordered:'failover sequence',labels:['API','Auth','Cache','Queue','Search','Storage'],roleLabels:['First','Second','Third','Fourth']})},
 restart:{id:'restart',title:'Full Restart Order',state:makeState({id:'restart',mode:'ordered',n:5,k:5,title:'Full Service Restart Order',objectNoun:'service',group:'service set',ordered:'restart order',labels:['API','Auth','Cache','Queue','Storage'],roleLabels:['Restart 1','Restart 2','Restart 3','Restart 4','Restart 5']})}
};
function loadPreset(id){if(!PRESETS[id])throw new RangeError(`Unknown preset ${id}`);return clone(PRESETS[id].state)}
function factorial(n){if(!Number.isInteger(n)||n<0)throw new RangeError('Factorial requires a nonnegative integer');let r=1;for(let i=2;i<=n;i++)r*=i;return r}
const getPermutationFactors=(n,k)=>Array.from({length:k},(_,i)=>n-i);
const permutations=(n,k)=>getPermutationFactors(n,k).reduce((p,v)=>p*v,1);
function combinations(n,k){const r=Math.min(k,n-k);let value=1;for(let i=1;i<=r;i++)value=value*(n-r+i)/i;return value}
const comboCache=new Map(),permCache=new Map();
function generateCombinations(n,k){const key=`${n},${k}`;if(comboCache.has(key))return comboCache.get(key);const out=[];function visit(start,path){if(path.length===k){out.push([...path]);return}for(let i=start;i<=n-(k-path.length);i++){path.push(i);visit(i+1,path);path.pop()}}visit(0,[]);comboCache.set(key,out);return out}
function generatePermutations(n,k){const key=`${n},${k}`;if(permCache.has(key))return permCache.get(key);const out=[],used=new Array(n).fill(false);function visit(path){if(path.length===k){out.push([...path]);return}for(let i=0;i<n;i++)if(!used[i]){used[i]=true;path.push(i);visit(path);path.pop();used[i]=false}}visit([]);permCache.set(key,out);return out}
function generateGroupOrders(group){const source=[...group].sort((a,b)=>a-b),out=[],used=new Array(source.length).fill(false);function visit(path){if(path.length===source.length){out.push([...path]);return}for(let i=0;i<source.length;i++)if(!used[i]){used[i]=true;path.push(source[i]);visit(path);path.pop();used[i]=false}}visit([]);return out}
const groupFromOrder=order=>[...order].sort((a,b)=>a-b),canonicalOrderFromGroup=group=>[...group].sort((a,b)=>a-b);
const same=(a,b)=>a.length===b.length&&a.every((v,i)=>v===b[i]);
const findCombinationIndex=(group,list)=>list.findIndex(x=>same(x,groupFromOrder(group)));
const findPermutationIndex=(order,list)=>list.findIndex(x=>same(x,order));
function counts(s){return{factorialN:factorial(s.n),factorialK:factorial(s.k),factorialNMinusK:factorial(s.n-s.k),permutationCount:permutations(s.n,s.k),combinationCount:combinations(s.n,s.k),descendingFactors:getPermutationFactors(s.n,s.k)}}
function validateState(s){const errors=[];if(!Number.isInteger(s.n)||s.n<1||s.n>10)errors.push({field:'n',message:'n must be a whole number from 1 to 10.'});if(!Number.isInteger(s.k)||s.k<0||s.k>5||s.k>s.n)errors.push({field:'k',message:'Selection size k must be a whole number from 0 through min(n,5).'});if(!s.language.title.trim()||!s.language.objectNoun.trim()||!s.language.groupOutcomeNoun.trim()||!s.language.orderedOutcomeNoun.trim())errors.push({field:'language',message:'Scenario title and outcome nouns cannot be empty.'});if(!Number.isInteger(s.n)||!Number.isInteger(s.k)||s.n<1||s.n>10||s.k<0||s.k>s.n)return errors;const active=s.objects.slice(0,s.n),labels=active.map(o=>o.label.trim().toLowerCase()),shorts=active.map(o=>o.shortLabel.trim().toLowerCase());if(active.some(o=>!o.label.trim()))errors.push({field:'objects',message:'Active object labels cannot be empty.'});if(new Set(labels).size<labels.length)errors.push({field:'objects',message:'Active object labels must identify distinct objects.'});if(active.some(o=>!o.shortLabel.trim()||[...o.shortLabel.trim()].length>3)||new Set(shorts).size<shorts.length)errors.push({field:'objects',message:'Active short labels must be unique and contain one to three characters.'});const roleLabels=s.roles.slice(0,s.k).map(r=>r.label.trim().toLowerCase());if(roleLabels.some(x=>!x)||new Set(roleLabels).size<roleLabels.length)errors.push({field:'roles',message:'Ordered roles must have distinct, nonempty labels.'});const group=groupFromOrder(s.selectedGroupIndices),order=s.selectedOrderIndices,validIndices=x=>x.length===s.k&&new Set(x).size===x.length&&x.every(i=>Number.isInteger(i)&&i>=0&&i<s.n);if(!validIndices(group)||!validIndices(order)||!same(group,groupFromOrder(order))||!same(group,s.selectedGroupIndices))errors.push({field:'selection',message:'The group and ordering must contain the same k distinct active objects.'});return errors}
function normalizeSelection(s){const valid=s.selectedOrderIndices.length===s.k&&new Set(s.selectedOrderIndices).size===s.k&&s.selectedOrderIndices.every(i=>i<s.n);if(!valid){const first=generateCombinations(s.n,s.k)[0];s.selectedGroupIndices=[...first];s.selectedOrderIndices=[...first]}else{s.selectedGroupIndices=groupFromOrder(s.selectedOrderIndices)}return s}
function selectedGlobalIndex(s){return s.mode==='ordered'?findPermutationIndex(s.selectedOrderIndices,generatePermutations(s.n,s.k)):findCombinationIndex(s.selectedGroupIndices,generateCombinations(s.n,s.k))}
function selectedBundleIndex(s){return findPermutationIndex(s.selectedOrderIndices,generateGroupOrders(s.selectedGroupIndices))}
function syncPages(s){const gi=selectedGlobalIndex(s),bi=selectedBundleIndex(s);s.globalOutcomePage=Math.max(0,Math.floor(gi/20));s.bundlePage=Math.max(0,Math.floor(bi/24));return s}
function buildOrderedTrace(s){return s.selectedOrderIndices.map((index,depth)=>`Depth ${depth}: choose ${s.objects[index].label} for ${s.roles[depth].label}; ${s.n-depth} choices ${depth?'remained':'were available'}`).concat([`Output ordered tuple (${s.selectedOrderIndices.map(i=>s.objects[i].label).join(', ')})`])}
function buildUnorderedTrace(s){const lines=s.selectedGroupIndices.map((index,i)=>`${i?'Continue after '+s.objects[s.selectedGroupIndices[i-1]].label:'Start at index 0'}: include ${s.objects[index].label}`);lines.push(`Output canonical set {${s.selectedGroupIndices.map(i=>s.objects[i].label).join(', ')}`+'}', 'Reordered copies are skipped because the search never returns to an earlier index');return lines}
return{DEFAULT_NAMES,IDS,COLORS,ROLE_NAMES,PRESETS,clone,loadPreset,factorial,getPermutationFactors,permutations,combinations,generateCombinations,generatePermutations,generateGroupOrders,groupFromOrder,canonicalOrderFromGroup,findCombinationIndex,findPermutationIndex,counts,validateState,normalizeSelection,selectedGlobalIndex,selectedBundleIndex,syncPages,buildOrderedTrace,buildUnorderedTrace};});
