(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.OverlapModel=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
function set(id,label,shortLabel,size,colorRole){return{id,label,shortLabel,size,colorRole}}
function product(enabled=false,label='Environments',choiceCount=4){return{enabled,label,choiceCount}}
const TWO_PRESETS={
  permissions:{id:'permissions',title:'Elevated Permissions',scenario:{kind:'two',title:'Elevated Permission Audit',sets:[set('a','Developer','D',42,'blue'),set('b','Administrator','A',30,'green')],intersectionAB:12,universeEnabled:true,universeSize:80,productStage:product()}},
  alerts:{id:'alerts',title:'Service Alerts',scenario:{kind:'two',title:'Service Alert Audit',sets:[set('a','Latency alert','L',28,'blue'),set('b','Error-rate alert','E',19,'green')],intersectionAB:7,universeEnabled:true,universeSize:60,productStage:product()}},
  checks:{id:'checks',title:'Passing Both Checks',scenario:{kind:'two',title:'System Check Audit',sets:[set('a','Network failure','N',25,'blue'),set('b','Storage failure','S',20,'green')],intersectionAB:7,universeEnabled:true,universeSize:240,productStage:product()}},
  product:{id:'product',title:'Product Audit',scenario:{kind:'two',title:'Permission Environment Audit',sets:[set('a','Developer','D',42,'blue'),set('b','Administrator','A',30,'green')],intersectionAB:12,universeEnabled:false,universeSize:80,productStage:product(true,'Environments',4)}}
};
const THREE_PRESETS={systems:{id:'systems',title:'Three Failure Systems',scenario:{kind:'three',title:'Three Failure Systems',sets:[set('a','Networking','N',20,'blue'),set('b','Storage','S',18,'green'),set('c','Authentication','A',15,'gold')],intersectionAB:7,intersectionAC:6,intersectionBC:5,intersectionABC:2,universeEnabled:true,universeSize:50,productStage:product()}}};
function makeObjects(n,noun='key'){return Array.from({length:n},(_,i)=>({id:`object-${i+1}`,label:`${noun.charAt(0).toUpperCase()}${i+1}`,containerId:null}))}
function makeContainers(n,noun='bucket'){return Array.from({length:n},(_,i)=>({id:`container-${i+1}`,label:`${noun.charAt(0).toUpperCase()}${i+1}`,colorIndex:i}))}
function assignRoundRobin(objects,containers){return objects.map((o,i)=>({...o,containerId:containers[i%containers.length].id}))}
function pigeonScenario(title,n,m,objectNoun,containerNoun,arrangement='none'){const containers=makeContainers(m,containerNoun),base=makeObjects(n,objectNoun);let objects=base;if(arrangement==='even')objects=assignRoundRobin(base,containers);if(arrangement==='first-ten')objects=base.map((o,i)=>({...o,containerId:i<10?containers[i].id:null}));return{title,objectNoun,containerNoun,objects,containers,selectedObjectId:null}}
const PIGEON_PRESETS={
  hash:{id:'hash',title:'Forced Hash Collision',scenario:pigeonScenario('Hash Bucket Collision',11,10,'key','bucket','first-ten')},
  jobs:{id:'jobs',title:'Server Jobs',scenario:pigeonScenario('Server Job Allocation',25,6,'job','server')},
  sessions:{id:'sessions',title:'Active Sessions',scenario:pigeonScenario('Active Session Allocation',18,4,'session','server','even')},
  requests:{id:'requests',title:'No Forced Collision Yet',scenario:pigeonScenario('Request Queue Allocation',8,10,'request','queue')}
};
function loadPreset(kind,key){const source=kind==='two'?TWO_PRESETS:kind==='three'?THREE_PRESETS:PIGEON_PRESETS;if(!source[key])throw new RangeError(`Unknown ${kind} preset: ${key}`);return clone(source[key].scenario)}
function deriveTwoSetRegions(input){const a=input.a??input.sets?.[0].size,b=input.b??input.sets?.[1].size,ab=input.ab??input.intersectionAB;return{aOnly:a-ab,abOnly:ab,bOnly:b-ab,union:a+b-ab}}
function deriveThreeSetRegions(input){const a=input.a??input.sets?.[0].size,b=input.b??input.sets?.[1].size,c=input.c??input.sets?.[2].size,ab=input.ab??input.intersectionAB,ac=input.ac??input.intersectionAC,bc=input.bc??input.intersectionBC,abc=input.abc??input.intersectionABC;const regions={aOnly:a-ab-ac+abc,bOnly:b-ab-bc+abc,cOnly:c-ac-bc+abc,abOnly:ab-abc,acOnly:ac-abc,bcOnly:bc-abc,abcOnly:abc};return{...regions,union:Object.values(regions).reduce((s,v)=>s+v,0)}}
const isInteger=(value,min,max)=>Number.isFinite(value)&&Number.isInteger(value)&&value>=min&&value<=max;
function sharedValidation(s){const errors=[];const labels=s.sets.map(x=>x.label.trim().toLowerCase()),shorts=s.sets.map(x=>x.shortLabel.trim().toLowerCase());s.sets.forEach((x,i)=>{if(!x.label.trim())errors.push({field:`set-${i}-label`,message:'Set labels cannot be empty.'});if(!isInteger(x.size,0,999))errors.push({field:`set-${i}-size`,message:`${x.label||`Set ${i+1}`} must be a whole number from 0 to 999.`});if(!x.shortLabel.trim()||[...x.shortLabel.trim()].length>3)errors.push({field:`set-${i}-short`,message:'Short labels must contain one to three visible characters.'})});if(new Set(labels).size<labels.length)errors.push({field:'sets',message:'Set labels must be unique.'});if(new Set(shorts).size<shorts.length)errors.push({field:'shorts',message:'Short labels must be unique.'});if(s.universeEnabled&&!isInteger(s.universeSize,0,5000))errors.push({field:'universeSize',message:'Universe size must be a whole number from 0 to 5000.'});if(s.productStage.enabled){if(!s.productStage.label.trim())errors.push({field:'productLabel',message:'Product-stage label cannot be empty.'});if(!isInteger(s.productStage.choiceCount,1,100))errors.push({field:'choiceCount',message:'Later choices must be a whole number from 1 to 100.'})}return errors}
function validateTwoSetScenario(s){const errors=sharedValidation(s);if(!isInteger(s.intersectionAB,0,999))errors.push({field:'intersectionAB',message:'The intersection must be a whole number from 0 to 999.'});if(errors.some(e=>e.field.includes('size')||e.field==='intersectionAB'))return errors;const limit=Math.min(s.sets[0].size,s.sets[1].size);if(s.intersectionAB>limit)errors.push({field:'intersectionAB',message:`The intersection cannot exceed either set. Reduce Both to ${limit} or less.`});const r=deriveTwoSetRegions(s);if(s.universeEnabled&&isInteger(s.universeSize,0,5000)&&r.union>s.universeSize)errors.push({field:'universeSize',message:`The union contains ${r.union} outcomes, but the universe contains only ${s.universeSize}.`});return errors}
function validateThreeSetScenario(s){const errors=sharedValidation(s),fields=['intersectionAB','intersectionAC','intersectionBC','intersectionABC'];for(const field of fields)if(!isInteger(s[field],0,999))errors.push({field,message:'Intersections must be whole numbers from 0 to 999.'});if(errors.some(e=>e.field.includes('size')||fields.includes(e.field)))return errors;const[a,b,c]=s.sets.map(x=>x.size),{intersectionAB:ab,intersectionAC:ac,intersectionBC:bc,intersectionABC:abc}=s;const centerError=(left,right,value)=>`The all-three intersection is ${abc}, but the ${left}-${right} intersection is only ${value}. Pairwise intersections must include the all-three region.`;if(abc>ab)errors.push({field:'intersectionABC',message:centerError(s.sets[0].label,s.sets[1].label,ab)});if(abc>ac)errors.push({field:'intersectionABC',message:centerError(s.sets[0].label,s.sets[2].label,ac)});if(abc>bc)errors.push({field:'intersectionABC',message:centerError(s.sets[1].label,s.sets[2].label,bc)});if(ab>Math.min(a,b))errors.push({field:'intersectionAB',message:'The first pairwise intersection cannot exceed either set.'});if(ac>Math.min(a,c))errors.push({field:'intersectionAC',message:'The second pairwise intersection cannot exceed either set.'});if(bc>Math.min(b,c))errors.push({field:'intersectionBC',message:'The third pairwise intersection cannot exceed either set.'});const r=deriveThreeSetRegions(s),names=[['aOnly',s.sets[0].label],['bOnly',s.sets[1].label],['cOnly',s.sets[2].label],['abOnly',`${s.sets[0].label} and ${s.sets[1].label}`],['acOnly',`${s.sets[0].label} and ${s.sets[2].label}`],['bcOnly',`${s.sets[1].label} and ${s.sets[2].label}`]];for(const[key,name]of names)if(r[key]<0)errors.push({field:key,message:`These values make ${name} only equal to ${r[key]}. Increase the set total or reduce its intersections.`});if(s.universeEnabled&&isInteger(s.universeSize,0,5000)&&r.union>s.universeSize)errors.push({field:'universeSize',message:`The seven Venn regions contain ${r.union} outcomes, which exceeds the universe of ${s.universeSize}.`});return errors}
function buildInclusionLedger(s){let running=0;const terms=s.kind==='two'?[{operation:'Add',term:s.sets[0].label,value:s.sets[0].size},{operation:'Add',term:s.sets[1].label,value:s.sets[1].size},{operation:'Subtract',term:'Both',value:-s.intersectionAB}]:[{operation:'Add',term:s.sets[0].label,value:s.sets[0].size},{operation:'Add',term:s.sets[1].label,value:s.sets[1].size},{operation:'Add',term:s.sets[2].label,value:s.sets[2].size},{operation:'Subtract',term:`${s.sets[0].label} and ${s.sets[1].label}`,value:-s.intersectionAB},{operation:'Subtract',term:`${s.sets[0].label} and ${s.sets[2].label}`,value:-s.intersectionAC},{operation:'Subtract',term:`${s.sets[1].label} and ${s.sets[2].label}`,value:-s.intersectionBC},{operation:'Add back',term:'All three',value:s.intersectionABC}];return terms.map((row,i)=>({...row,step:i+1,running:running+=row.value}))}
function getSelectedRegionContribution(regionId,setCount){if(setCount===2)return regionId==='abOnly'?{equation:'2 - 1 = 1',text:'Added once in each set, then subtracted once as part of the intersection.'}:{equation:'1 = 1',text:'This outcome appears in exactly one set total.'};if(regionId==='abcOnly')return{equation:'3 - 3 + 1 = 1',text:'Added once in A, once in B, and once in C: 3 contributions. Subtracted once in each pairwise intersection: -3 contributions. Added back once in the triple intersection: +1 contribution.'};if(['abOnly','acOnly','bcOnly'].includes(regionId))return{equation:'2 - 1 = 1',text:'Added in two set totals and subtracted once in their pairwise intersection.'};return{equation:'1 = 1',text:'This outcome appears in exactly one set total.'}}
const getComplement=(universe,union)=>universe-union,getProductTotal=(union,choices)=>union*choices,pigeonholeBound=(N,m)=>Math.ceil(N/m);
function getContainerLoads(objects,containers){const loads=new Map(containers.map(c=>[c.id,0]));for(const o of objects)if(o.containerId!==null&&loads.has(o.containerId))loads.set(o.containerId,loads.get(o.containerId)+1);return loads}
function getExactMaximumLoad(loads){return Math.max(0,...loads.values())}
const isAssignmentComplete=objects=>objects.every(o=>o.containerId!==null);
function validatePigeonhole(s){const errors=[];if(s.objects.length<1||s.objects.length>30)errors.push({field:'objectCount',message:'Use 1 to 30 objects.'});if(s.containers.length<1||s.containers.length>12)errors.push({field:'containerCount',message:'Use 1 to 12 containers.'});for(const[key,items]of[['Object',s.objects],['Container',s.containers]]){if(items.some(x=>!x.label.trim()))errors.push({field:key.toLowerCase(),message:`${key} labels cannot be empty.`});const labels=items.map(x=>x.label.trim().toLowerCase());if(new Set(labels).size<labels.length)errors.push({field:key.toLowerCase(),message:`${key} labels must be unique.`})}return errors}
function resizeObjects(s,n){if(!isInteger(n,1,30))return s;const objects=s.objects.slice(0,n);for(let i=objects.length;i<n;i++)objects.push({id:`object-${i+1}`,label:`${s.objectNoun.charAt(0).toUpperCase()}${i+1}`,containerId:null});return{...s,objects,selectedObjectId:objects.some(o=>o.id===s.selectedObjectId)?s.selectedObjectId:null}}
function resizeContainers(s,n){if(!isInteger(n,1,12))return s;const containers=s.containers.slice(0,n);for(let i=containers.length;i<n;i++)containers.push({id:`container-${i+1}`,label:`${s.containerNoun.charAt(0).toUpperCase()}${i+1}`,colorIndex:i});const ids=new Set(containers.map(c=>c.id)),objects=s.objects.map(o=>({...o,containerId:ids.has(o.containerId)?o.containerId:null}));return{...s,containers,objects,selectedObjectId:s.selectedObjectId}}
return{TWO_PRESETS,THREE_PRESETS,PIGEON_PRESETS,clone,loadPreset,deriveTwoSetRegions,deriveThreeSetRegions,validateTwoSetScenario,validateThreeSetScenario,buildInclusionLedger,getSelectedRegionContribution,getComplement,getProductTotal,pigeonholeBound,getContainerLoads,getExactMaximumLoad,isAssignmentComplete,assignRoundRobin,validatePigeonhole,resizeObjects,resizeContainers};});
